language: node_js
node_js:
  - "v10.15.3"

cache: npm

before_script:
  - npm install

script:
  - npm run render

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master